package programadopsihewan;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;

public class PanelDataHewan extends javax.swing.JPanel {

    private DefaultTableModel modelHewan;
    private List<Hewan> daftarHewanSaatIni;
    private int idHewanTerpilih = -1; 

    private final HewanDAO hewanDAO = new HewanDAO();

    /**
     * Creates new form PanelDataHewan
     */
    public PanelDataHewan() {
        initComponents();

        modelHewan = new DefaultTableModel(
                new String[]{"ID", "Jenis", "Nama", "Umur (bln)", "Berat (kg)", "Status", "Biaya Adopsi"}, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tbHewan.setModel(modelHewan);

        refreshTabelHewan();
        updateLabelAtributKhusus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbHewan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboJenisHewan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txNamaHewan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txUmurHewan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txBeratHewan = new javax.swing.JTextField();
        lblAtributKhusus = new javax.swing.JLabel();
        txAtributKhusus = new javax.swing.JTextField();
        cmdSimpanHewan = new javax.swing.JButton();
        cmdUpdateHewan = new javax.swing.JButton();
        cmdHapusHewan = new javax.swing.JButton();
        cmdBersihkanHewan = new javax.swing.JButton();

        tbHewan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Jenis", "Nama", "Umur (bln)", "Berat (kg)", "Status", "Biaya Adopsi"
            }
        ));
        tbHewan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHewanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHewan);

        jLabel1.setText("Jenis Hewan:");

        cboJenisHewan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kucing", "Anjing", "Burung", "Kera" }));
        cboJenisHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboJenisHewanActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Hewan:");
        jLabel3.setText("Umur (bulan):");
        jLabel4.setText("Berat (kg):");
        lblAtributKhusus.setText("Jenis Bulu:");

        cmdSimpanHewan.setText("Simpan Data Baru");
        cmdSimpanHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSimpanHewanActionPerformed(evt);
            }
        });

        cmdUpdateHewan.setText("Update Data");
        cmdUpdateHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateHewanActionPerformed(evt);
            }
        });

        cmdHapusHewan.setText("Hapus Data");
        cmdHapusHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusHewanActionPerformed(evt);
            }
        });

        cmdBersihkanHewan.setText("Bersihkan Form");
        cmdBersihkanHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBersihkanHewanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboJenisHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNamaHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txUmurHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txBeratHewan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblAtributKhusus, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txAtributKhusus, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cmdSimpanHewan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdUpdateHewan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdHapusHewan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdBersihkanHewan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboJenisHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNamaHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txUmurHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txBeratHewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtributKhusus)
                    .addComponent(txAtributKhusus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSimpanHewan)
                    .addComponent(cmdUpdateHewan)
                    .addComponent(cmdHapusHewan)
                    .addComponent(cmdBersihkanHewan))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboJenisHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboJenisHewanActionPerformed
        updateLabelAtributKhusus();
    }//GEN-LAST:event_cboJenisHewanActionPerformed

    private void tbHewanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHewanMouseClicked
        isiFormDariTabel();
    }//GEN-LAST:event_tbHewanMouseClicked

    private void cmdSimpanHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSimpanHewanActionPerformed
        simpanHewan();
    }//GEN-LAST:event_cmdSimpanHewanActionPerformed

    private void cmdUpdateHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateHewanActionPerformed
        updateHewan();
    }//GEN-LAST:event_cmdUpdateHewanActionPerformed

    private void cmdHapusHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusHewanActionPerformed
        hapusHewan();
    }//GEN-LAST:event_cmdHapusHewanActionPerformed

    private void cmdBersihkanHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBersihkanHewanActionPerformed
        bersihkanFormHewan();
    }//GEN-LAST:event_cmdBersihkanHewanActionPerformed

    // ================= LOGIC =================

    private void updateLabelAtributKhusus() {
        String jenis = (String) cboJenisHewan.getSelectedItem();
        switch (jenis) {
            case "Kucing": lblAtributKhusus.setText("Jenis Bulu:"); break;
            case "Anjing": lblAtributKhusus.setText("Jenis Ras:"); break;
            case "Burung": lblAtributKhusus.setText("Kemampuan Bicara:"); break;
            case "Kera":   lblAtributKhusus.setText("Tingkat Kejinakan:"); break;
            default:       lblAtributKhusus.setText("Atribut Khusus:");
        }
    }

    private void refreshTabelHewan() {
        daftarHewanSaatIni = hewanDAO.tampilkanSemua();
        modelHewan.setRowCount(0);
        for (Hewan h : daftarHewanSaatIni) {
            modelHewan.addRow(new Object[]{
                h.getId(), h.getJenis(), h.getNama(), h.getUmur(), h.getBeratBadan(),
                h.isSudahDiadopsi() ? "Sudah Diadopsi" : "Tersedia",
                "Rp" + String.format("%,.0f", h.hitungBiayaAdopsi())
            });
        }
    }

    private void isiFormDariTabel() {
        int row = tbHewan.getSelectedRow();
        if (row < 0 || row >= daftarHewanSaatIni.size()) return;

        Hewan h = daftarHewanSaatIni.get(row);
        idHewanTerpilih = h.getId();

        cboJenisHewan.setSelectedItem(h.getJenis());
        updateLabelAtributKhusus();
        txNamaHewan.setText(h.getNama());
        txUmurHewan.setText(String.valueOf(h.getUmur()));
        txBeratHewan.setText(String.valueOf(h.getBeratBadan()));
        txAtributKhusus.setText(h.getAtributKhusus());
    }

    private void simpanHewan() {
        try {
            String jenis = (String) cboJenisHewan.getSelectedItem();
            String nama = txNamaHewan.getText().trim();
            if (nama.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama hewan tidak boleh kosong!", "Validasi", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int umur = Integer.parseInt(txUmurHewan.getText().trim());
            double berat = Double.parseDouble(txBeratHewan.getText().trim());

            Hewan h = buatObjekHewan(jenis, nama, umur, berat, false, txAtributKhusus.getText().trim());

            if (hewanDAO.simpan(h)) {
                JOptionPane.showMessageDialog(this, "Data hewan berhasil disimpan!");
                refreshTabelHewan();
                bersihkanFormHewan();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Umur dan Berat harus berupa angka!", "Validasi", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void updateHewan() {
        if (idHewanTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu data di tabel yang mau diupdate.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            String jenis = (String) cboJenisHewan.getSelectedItem();
            String nama = txNamaHewan.getText().trim();
            int umur = Integer.parseInt(txUmurHewan.getText().trim());
            double berat = Double.parseDouble(txBeratHewan.getText().trim());

            Hewan h = buatObjekHewan(jenis, nama, umur, berat, false, txAtributKhusus.getText().trim());
            h.setId(idHewanTerpilih);

            if (hewanDAO.update(h)) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
                refreshTabelHewan();
                bersihkanFormHewan();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal update data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Umur dan Berat harus berupa angka!", "Validasi", JOptionPane.WARNING_MESSAGE);
        }
    }

    private Hewan buatObjekHewan(String jenis, String nama, int umur, double berat,
                                  boolean sudahDiadopsi, String atribut) {
        switch (jenis) {
            case "Kucing": return new Kucing(nama, umur, berat, sudahDiadopsi, atribut);
            case "Anjing": return new Anjing(nama, umur, berat, sudahDiadopsi, atribut);
            case "Burung": return new Burung(nama, umur, berat, sudahDiadopsi, atribut);
            case "Kera":   return new Kera(nama, umur, berat, sudahDiadopsi, atribut);
            default: throw new IllegalArgumentException("Jenis hewan tidak dikenali: " + jenis);
        }
    }

    private void hapusHewan() {
        if (idHewanTerpilih == -1) {
            JOptionPane.showMessageDialog(this, "Pilih dulu data di tabel yang mau dihapus.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin mau hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            if (hewanDAO.hapus(idHewanTerpilih)) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                refreshTabelHewan();
                bersihkanFormHewan();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void bersihkanFormHewan() {
        idHewanTerpilih = -1;
        txNamaHewan.setText("");
        txUmurHewan.setText("");
        txBeratHewan.setText("");
        txAtributKhusus.setText("");
        cboJenisHewan.setSelectedIndex(0);
        updateLabelAtributKhusus();
    }

    public void refreshData() {
        refreshTabelHewan();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboJenisHewan;
    private javax.swing.JButton cmdBersihkanHewan;
    private javax.swing.JButton cmdHapusHewan;
    private javax.swing.JButton cmdSimpanHewan;
    private javax.swing.JButton cmdUpdateHewan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAtributKhusus;
    private javax.swing.JTable tbHewan;
    private javax.swing.JTextField txAtributKhusus;
    private javax.swing.JTextField txBeratHewan;
    private javax.swing.JTextField txNamaHewan;
    private javax.swing.JTextField txUmurHewan;
    // End of variables declaration//GEN-END:variables
}
