package programadopsihewan;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.List;

public class PanelProsesAdopsi extends javax.swing.JPanel {

    private DefaultTableModel modelPengadopsi;
    private List<Hewan> daftarHewanTersedia;

    private final HewanDAO hewanDAO = new HewanDAO();
    private final PengadopsiDAO pengadopsiDAO = new PengadopsiDAO();

    /**
     * Creates new form PanelProsesAdopsi
     */
    public PanelProsesAdopsi() {
        initComponents();

        modelPengadopsi = new DefaultTableModel(
                new String[]{"ID", "Nama", "Alamat", "No Telp", "Tanggal", "Hewan Diadopsi"}, 0) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        tbPengadopsi.setModel(modelPengadopsi);

        txTanggalAdopsi.setText(java.time.LocalDate.now().toString());

        refreshComboHewanTersedia();
        refreshTabelPengadopsi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboHewanTersedia = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txNamaPengadopsi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txAlamatPengadopsi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txNoTelpPengadopsi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txEmailPengadopsi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txTanggalAdopsi = new javax.swing.JTextField();
        cmdProsesAdopsi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPengadopsi = new javax.swing.JTable();

        jLabel1.setText("Pilih Hewan (tersedia):");
        jLabel2.setText("Nama Pengadopsi:");
        jLabel3.setText("Alamat:");
        jLabel4.setText("No Telp:");
        jLabel5.setText("Email:");
        jLabel6.setText("Tanggal Adopsi (yyyy-mm-dd):");

        cmdProsesAdopsi.setText("Proses Adopsi");
        cmdProsesAdopsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProsesAdopsiActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Riwayat Adopsi"));
        tbPengadopsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "Alamat", "No Telp", "Tanggal", "Hewan Diadopsi"
            }
        ));
        jScrollPane1.setViewportView(tbPengadopsi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboHewanTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNamaPengadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txAlamatPengadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNoTelpPengadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txEmailPengadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txTanggalAdopsi, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(cmdProsesAdopsi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboHewanTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txNamaPengadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txAlamatPengadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txNoTelpPengadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txEmailPengadopsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txTanggalAdopsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(cmdProsesAdopsi)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdProsesAdopsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProsesAdopsiActionPerformed
        prosesAdopsi();
    }//GEN-LAST:event_cmdProsesAdopsiActionPerformed

    // ================= LOGIC =================

    private void refreshComboHewanTersedia() {
        daftarHewanTersedia = hewanDAO.tampilkanTersedia();
        cboHewanTersedia.removeAllItems();
        for (Hewan h : daftarHewanTersedia) {
            cboHewanTersedia.addItem(h.getId() + " - " + h.getNama() + " (" + h.getJenis() + ")");
        }
    }

    private void refreshTabelPengadopsi() {
        modelPengadopsi.setRowCount(0);
        for (String[] row : pengadopsiDAO.tampilkanSemua()) {
            modelPengadopsi.addRow(row);
        }
    }

    private void prosesAdopsi() {
        if (cboHewanTersedia.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Tidak ada hewan yang tersedia untuk diadopsi.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        try {
            String nama = txNamaPengadopsi.getText().trim();
            String alamat = txAlamatPengadopsi.getText().trim();
            String noTelp = txNoTelpPengadopsi.getText().trim();
            String email = txEmailPengadopsi.getText().trim();

            if (nama.isEmpty() || alamat.isEmpty() || noTelp.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama, alamat, dan no telp wajib diisi!", "Validasi", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Date tanggal = Date.valueOf(txTanggalAdopsi.getText().trim());

            String pilihan = (String) cboHewanTersedia.getSelectedItem();
            int hewanId = Integer.parseInt(pilihan.split(" - ")[0]);

            Pengadopsi p = new Pengadopsi(nama, alamat, noTelp, email, tanggal, hewanId);

            if (pengadopsiDAO.simpanAdopsi(p)) {
                JOptionPane.showMessageDialog(this, "Adopsi berhasil diproses!");
                txNamaPengadopsi.setText("");
                txAlamatPengadopsi.setText("");
                txNoTelpPengadopsi.setText("");
                txEmailPengadopsi.setText("");
                refreshComboHewanTersedia();
                refreshTabelPengadopsi();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memproses adopsi.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "Format tanggal salah! Gunakan yyyy-mm-dd.", "Validasi", JOptionPane.WARNING_MESSAGE);
        }
    }

    public void refreshData() {
        refreshComboHewanTersedia();
        refreshTabelPengadopsi();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboHewanTersedia;
    private javax.swing.JButton cmdProsesAdopsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPengadopsi;
    private javax.swing.JTextField txAlamatPengadopsi;
    private javax.swing.JTextField txEmailPengadopsi;
    private javax.swing.JTextField txNamaPengadopsi;
    private javax.swing.JTextField txNoTelpPengadopsi;
    private javax.swing.JTextField txTanggalAdopsi;
    // End of variables declaration//GEN-END:variables
}
